name = "g-health"
main = "src/worker.ts"
compatibility_date = "2026-04-12"

[env.production]
routes = [
  { pattern = "https://g-health.sripriyagorti4499.workers.dev/", zone_id = "" }
]

[env.development]
vars = { ENVIRONMENT = "development" }

[vars]
ENVIRONMENT = "development"

[secrets]
# Add via: wrangler secret put MONGODB_URI
# Add via: wrangler secret put GEMINI_API_KEY
